<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lab 2: Let‚Äôs 3D Print a Rotating Keychain!</title>
    <!-- Bootswatch Litera CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/litera/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="../../styles.css"></link>
</head>
<body>

    <!-- Header Placeholder -->
    <div id="header-placeholder"></div>

    <!-- Main Container -->
    <div class="container" >
    <div class="row">
        <!-- Lab 1 Page Heading -->        
        <div class="col-md-4">
            <div class="sticky-top" style="padding-top:100px;" >
                <p>Total Time: 2.5 hours</p>
                <h5>Quick Links</h5>
                <ul>
                    <li><a href="#introduction">Introduction & Safety</a></li>
                    <li><a href="#software">Fabrication Quest</a></li>
                    <li><a href="#ppe">Software & Hardware for the Lab</a></li>
                    <li><a href="#machines">Part (1): Sketching Objects and Dimensioning </a></li>
                    <li><a href="#assembly">  Part (2): Mirroring Sketch Geometries </a></li>
                    <li><a href="#testing"> Part(3): Filletting</a></li>
                    <li><a href="#conclusion"> Part(4): Linear Patterning</a></li>
                      <li><a href="#machines">Part (5): Importing DXF files </a></li>
                    <li><a href="#assembly">  Part (6): Remixing </a></li>
                    <li><a href="#testing"> Part(7): Exporting DXF files</a></li>
                    <li><a href="#conclusion"> Part(8): Laser Cutting</a></li>
                    <li><a href="#conclusion"> Part(9): Spray Painting</a></li>
                    <li><a href="#conclusion"> Part(10): Assembly and Post-Processing</a></li>
                     <li><a href="#conclusion"> Part(11): Above and Beyond</a></li>
                </ul>
            </div>
        </div>
        
        <!-- Introduction Section -->
        <div class="col-md-8" style="padding-top:100px;">
                <section class="mb-4">
                    <h1 class="mb-5">Lab 2: Let‚Äôs 3D Print a Rotating Keychain!</h1>
                    <img src=media/placeholder.png class="rounded mx-auto d-block img-fluid"> 
                    <h2> ü¶∫ Introduction & Safety</h2>(1 minute read) <br> <br>
                    <p>
3D printing is an additive (add material) manufacturing process where computer-aided G-code (instruction code for the machine) is translated to build up
                        material layer by layer. It has various techniques, including <a href="https://www.hubs.com/knowledge-base/what-is-fdm-3d-printing/"> FDM </a>, which extrudes hot <a href="https://pslc.ws/macrog/plastic.htm" > thermoplastics </a> 
                        (plastics that melt at elevated temperatures), 
                        <a href="https://formlabs.com/blog/ultimate-guide-to-stereolithography-sla-3d-printing/">SLA</a>, which uses photoresin polymers that cure via light, and
                        <a href="https://www.stratasys.com/en/guide-to-3d-printing/technologies-and-materials/polyjet-technology/">Polyjet 3D printing</a>, among others.</p>
                    In this lab, you will <b> learn</b> how to: 
                    <br> <br> 
                    <ul>
                        <li> ‚úÖ Create 3D-models from 2D-sketches (extrusion and revolving operations) </li>
                        <li> ‚úÖ CAD a simple rotating element around a shaft</li>
                        <li> ‚úÖ CAD a threaded object</li>
                         <li> ‚úÖ Make a Mechanical Assembly </li>
                        <li> ‚úÖ Render a 3D Model in Fusion360</li>
                        <li> ‚úÖ Export files and prepare them for 3D printing 
</li>
                    </ul>

                </section>
                <hr>


                    <img src=media/placeholder.png class="rounded mx-auto d-block img-fluid"> 
                <br>
                    <h2>üî® Fabrication Quest of the Day</h2>
                <ul>
                    <li><strong>Today, you will CAD 4-5 parts:</strong>
                        <ul>
                            <li>(A) Threaded Shaft (<strong>x1</strong>)-- allows Remixing</li>
                            <li> (B) Rotating Blocks  (<strong>x3-4</strong>)-- allows Remixing</li>
                        </ul>
                    </li>
                    
            <li><strong>Fabricated results will be for next lab, but  you will put your files on the 3D printer today; </strong>

<br> <br> 
                <b>Your instructors will provide you with the following:</b>
                <ul>
                <li>(C) The screw cap (<strong>x1</strong>)</li>
                </ul>


                <hr>
                

                <!-- Materials Section -->
                <section class="mb-4">
                    <h2>üèóÔ∏è Software & Hardware</h2>


                    <h5>Software:</h5>
                        <ul>
                            <li> <a href="https://www.autodesk.com/education/edu-software/fusion"> Fusion360 </a> </li>
                            <li> <a href= "https://ultimaker.com/software/ultimaker-cura/"> Ultimaker Cura </a> (Ultimaker 3D Printer Slicing Program) </li>
                    
                    </ul>


                        <h5>Machines:</h5>
                        <ul>
                    <li>FDM 3D Printer</li>
                        </ul>

                </section>

                <hr>

                <!-- Procedure Section -->

                    
                    <!-- Part 1: Designing the Calendar -->
                    <h4>Part (1): Creating Variables & Equations for Dynamic Dimensioning! (10 minutes)

</h4>
  <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/6S8xpPzyGAQ?si=et1cR-XHRD9FAPry" title="YouTube video player" allowfullscreen></iframe>
        </div>

     <br> 
                
                <!--note that thread size is 7mmx1mm by making a hole--> 
                <strong> Video Summary </strong> 
       
                <ol>
        <li>Dimensioning models through variables allows for model dimension modification with ease</li>
        <li> To create dimension variables go to: <b>  Modify -> Change Parameters -> Add User Parameter (top "+" sign) </b> </li>
                    <li>Create a variable for ‚Äúshaft_outer_d‚Äù representing the inner diameter of the Threaded Shaft, and set it to 9mm.</li>
        <li>Follow table below to add all the following variables, and one equation to your Fusion File Parameters. Don't forget to save as you go! </li>
    </ol>
                <br> 
                
                
                <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
        <th scope="col">Part Name (do not add to Fusion)</th>
      <th scope="col">Variable Name (add in Fusion)</th>
      <th scope="col">Expression</th>
      <th scope="col">Unit</th>
    </tr>
  </thead>
  <tbody>

      
    <tr>
      <th scope="row">2</th>
      <td> Shaft Outer Diamter</td>
      <td>shaft_outer_d</td>
      <td>9</td>
      <td>mm</td>


    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Shaft Length for 3 Rotating Blocks</td>
      <td>shaft_length_3b</td>
      <td>36.2 </td>
      <td>mm</td>
    </tr>
 
      
 
    <tr>
      <th scope="row">4</th>
      <td>Shaft Length for 4 Rotating Blocks</td>
      <td>shaft_length_4b</td>
      <td>48.2 </td>
      <td>mm</td>
    </tr>
      
          <tr>
      <th scope="row">5</th>
      <td>Shaft Threaded Hole Depth</td>
      <td>thread_depth</td>
      <td>10</td>
      <td>mm</td>
              

      
            <tr>
      <th scope="row">7</th>
      <td>Keychain Hole Diameter</td>
      <td>keychain_hole_d</td>
      <td>4</td>
      <td>mm</td>
    </tr>
               <tr>
      <th scope="row">9</th>
      <td>Rotating Block Size</td>
      <td>rot_b_size</td>
      <td>12</td>
      <td>mm</td>
    </tr>   
 
               <tr>
      <th scope="row">10</th>
      <td>Rotating Block thickness</td>
      <td>rot_b_thick</td>
      <td>12</td>
      <td>mm</td>
    </tr>
      
               <tr>
      <th scope="row">11</th>
      <td>Rotating Block Hole Tolerance</td>
      <td>tolerance</td>
      <td>0.6</td>
      <td>mm</td>
    </tr>  

                <tr>
      <th scope="row">12</th>
      <td>Rotating Block Hole Diameter</td>
      <td>rot_b_hole_d</td>
      <td>shaft_outer_d + tolerance</td>
      <td>mm</td>
    </tr>  
           
      
  </tbody>
</table>
                
                
                    <div class="alert alert-info" role="alert" style="background-color: #C94747; color: white;">
                        <h4>Checkoff 1</h4>
                        Ask your instructor for a check-off on completing Part (1)
                    </div>
        <br> 
                    <hr> 
                    
                    <h4>Part (2): Sketch and Dimension Parametrically  (Sketching Keychain Shaft) (5 minutes)</h4>

                    <img src=media/3dprinting-pt2.png class="rounded mx-auto d-block img-fluid"> 


                <br>
                
                <strong> Instructions </strong> 
       
             
                <br> 
                
        <ol>
        <li>Draw a circle at the center (0,0).</li>
        <li>Dimension the first circle with ‚Äúshaft_outer_d.‚Äù</li>
        <li> Exit Sketch, and rename the Sketch to "shaft-circle"</li>
                </ol>
                <br>
                
                üìç If you need a refresher on how to sketch or dimension, please visit <a href="lab1.html"> Lab 1</a> !
                <br> 
   
                    
         <hr>
                    <!-- Part 4: Assembly and Post-Processing -->
            <h4>Part (3): Extruding the Sketch (give height to the shaft!) (5 minutes)</h4>
                    
                    
                    
                            
            <br> 
                
                                <strong> Video Summary </strong> 
<br> 

                <ol>
        <li>Click on <strong>Create</strong>.</li>
        <li>Select the <strong>Extrude Tool</strong>.</li>
        <li>Under <strong>Profile</strong>, select the area formed by the circle from your "shaft-circle" sketch.</li>
        <li>Set the <strong>Direction</strong> to <strong>One Side</strong>.</li>
        <li>Type the <strong>Distance</strong> as ‚Äúshaft_length_3b‚Äù or "shaft_length_4b"-- here you must decide whether you
                    will make a 3 block or 4 block keychain; No worries if you change your mind later on! ü§ó</li>
        <li>Choose the operation as <strong>New Component</strong>.</li>
        <li>Click <strong>Ok</strong> to create the solid cylinder.</li>
                    <li> Write click on the component and <strong> Rename it</strong> to "Shaft"</li>
    </ol>
                
                <br> 
                   
        <hr>
            
                    <h4>Part (4): Making a Threaded Hole (7 minutes)</h4>

                <br> 
<b> Video Summary: </b>   
            
                <ol>
        <li> Toggle "Shaft-circle" sketch back on</li>
        <li>Go to <strong>Create</strong>.</li>
        <li>Select the <strong>"Hole" Tool</strong>.</li>
        <li>Under <strong>Face</strong>, select the top face of the cylinder.</li>
        <li>Set the <strong>Reference</strong> to <strong>the center of the circle sketch</strong> (i.e. the "point" at the circle's center from the sketch).</li>
        <li>Set the <strong>Hole Type</strong> to <b> ‚ÄúSimple‚Äù </b></li>
        <li>Set the <strong>Hole Tap Type</strong> to <b> ‚ÄúTapped‚Äù </b></li>
        <li>Set the <strong>Thread Offset</strong> to <b> ‚ÄúFull‚Äù </b></li>
        <li>Set the <strong>Drill Point</strong> to <b> ‚ÄúAngle‚Äù </b></li>
        <li>Set the <strong>Depth</strong> to <b> "thread_depth" </b></li>
        <li>Set the <strong>Size</strong> to <b> 7mm </b></li>
         <li>Set the <strong>Designation</strong> to <b> M7mmx1mm </b></li>
         <li>Have <strong>Modeled</strong> checked <b> ON </b></li>
        <li>Click <strong>Ok</strong> to create your threaded hole.</li>
    </ol>
                <br> 
             
              <div class="alert alert-info" role="alert" style="background-color: #C94747; color: white;">

                        <h4>Checkoff 2</h4>
                    Show your shaft with its threaded hole to your instructor, and explain to them what M7mmx1mm means (you are encouraged to look up the answer online üëÄ)!
                    
                    </div>  
                

                <hr>

                                
                <hr> 
        <h4>Part (5): Creating Profile of Keychain Holder Head (10 minutes)</h4>

            <ol>
        <li>
            <strong>Create an Axis Through the Cylinder:</strong>
            <ul>
                <li>Go to the <strong>Construct</strong> command in the top menu.</li>
                <li>Select <strong>Axis Through Cylinder</strong>.</li>
                <li>Click on the cylinder to establish the axis of rotation.</li>
            </ul>
        </li>
        <li>
            <strong>Create a Plane at an Angle to the Axis:</strong>
            <ul>
                <li>Again, in the <strong>Construct</strong> menu, select <strong>Plane at Angle</strong>.</li>
                <li>Click on the axis you created.</li>
                <li>Enter the angle as "0" for the plane, then confirm.</li>
            </ul>
        </li>
        <li>
            <strong>Use the Plane to Sketch the profile for the Top Holder on [üö® REMIX OPPORTUNITYüö®]:</strong>
            
                                <img src=media/revolve-profiles.png class="rounded mx-auto d-block img-fluid"> 

            
            <ul>
                <li>On the new plane, right click on it and select <strong>Create New Sketch</strong> (there are other ways 
                    of doing this, but we opt for right clicking on plane for now).</li>
                <li> To ensure we remain within bounds, go to <strong> Create</strong>, then <strong> Project</strong>, <strong> Select Entity (Selection Filter)</strong> and click on the perimeter of the top circle of the cylinder for <strong> Geometry</strong>. Kepp Projection Link on.
                
                <li> Your Design Constraints for your REMIX are as follows: </li>
                <li>Draw the profile you would be revolving for the top holder on this plane. Recall that this should be symmetric and should not extrude out too much. Make sure that the profile is <strong> closed!</strong></li>
                <li>Once done, click <strong>Finish Sketch</strong></li>
            </ul>
        </li>
    </ol>
                
                <br> 
                
                In the next step, we will revolve this profile to create a symmetric top keychain holder.
                    <br> 
                
                <div class="alert alert-info" role="alert" style="background-color: #C94747; color: white;">

                        <h4>Checkoff 4</h4>
        Show & explain your sketched profile to your instructor ensuring that your design meets Remix Design Constraints!           </div>
        <hr> 
                
                
                
                <h4>Part (6): Revolving Radially Symmetric Geometry(10 minutes)</h4>

            <strong> Video Summary:</strong>
                
                 <ol>
        <li><strong>Revolve Command:</strong> Go to <strong>Create &gt; Revolve</strong> in the toolbar.</li>
        <li><strong>Select Profile:</strong> Click on the profile (the closed shape) that you want to revolve.</li>
        <li><strong>Select Axis:</strong> Click the axis of symmetry (the cyliner axis we constructed) around which the profile will revolve.</li>
        <li><strong>Set Angle:</strong> In the Revolve dialog, set the <strong>angle</strong> to 360¬∞ (or the desired angle for partial revolution if you want to play around with this!).</li>
        <li><strong>OK:</strong> Click <strong>OK</strong> to complete the operation.</li>
    </ol>
        
            
                <br>
        <div class="alert alert-info" role="alert" style="background-color: #C94747; color: white;">

                        <h4>Checkoff 7</h4>
        Show your Remix to your instructor!            </div>
        <hr> 
                
                <hr> 
                
                
                
                <h4>Part (7): Making Hole for Keychain (5 minutes)</h4>
                
        <ol>
        <li><strong>Create a Tangent Plane:</strong> Create a plane that is tangent to the surface of your revolved part using <strong>Construct &gt; Tangent Plane</strong>.</li>
        <li><strong>Sketch a Circle on the Tangent Plane:</strong> Start a sketch on the tangent plane and draw a circle where you want the hole.</li>
        <li><strong>Dimension the Circle:</strong> Use the <strong>Dimension</strong> tool to set the circle's diameter to <strong>4mm</strong> (or your desired size).</li>
        <li><strong>Extrude Cut the Hole:</strong> Use <strong>Create &gt; Extrude</strong>, select the circle, and set it to <strong>Cut</strong> with the <strong>Symmetric</strong> direction to cut both sides of the part.</li>
        <li><strong>Finish:</strong> Click <strong>OK</strong> to complete the hole creation process.</li>
    </ol>
                
                <br> 
        <div class="alert alert-info" role="alert" style="background-color: #C94747; color: white;">

                        <h4>Checkoff 8</h4>
        Show your shaft's keychain hole to your instructor       </div>      
                <hr> 

            <h4>Part 9: Creating Blocks (üö®REMIXüö®) (30 minutes)</h4>

                
                Recommend creating as "components" even though video shows Bodies
                Video goes here to show;
                <br> 
                
                 Be as creative as you can here! Below are some of your instructor's creations-- you might 
                also consider designing something in illustrator and importing as DXF (like what you learned in Lab1).
                
                
                                                <img src=media/block-examples.png class="rounded mx-auto d-block img-fluid"> 

                
                However your design constraints are as follows: 
                
                1) size of hole 
                2) extrusion size of keychain
                3) max size of a single block (you can add and subtract from some as long 
                as your combined size does not go beyond the length of your shaft-- there is a 0.2mm margin in your shaft length so things can slide a tiny bit;)
                <br> 
                
                
                <hr> 

            
                
                
        <h4>Part 10: Assigning Materials & Colors (15 minutes)</h4>

                          
<hr> 
                
   <h4>Part 11: Assemblies in CAD (15 minutes)</h4>

                

            <hr> 
                
                 <h4>Part 13: Rendering (5 minutes)</h4>
            <hr> 

                
 <h4>Part 13: Export for 3D Printing (5 minutes)</h4>

  <hr> 
                
                
  <h4>Part 14: Setting Up File for 3D Printing (5 minutes)</h4>


                
                <!-- Submission Section -->
                <section class="mb-4">
                    <h2>Discussion & Reflections</h2>
        <ol>
            <li><strong>Discuss the advantages and limitations of using laser cutting for digital fabrication.</strong>
                <ul>
                    <li>What can we make? What is difficult to make?</li>
                </ul>
            </li>
            <li><strong>Reflect on the design process</strong> 
                <ul>
                    <li>Consider any modifications that could improve future projects.</li>
                </ul>
            </li>
            
        </ol>
                </section>
                
                    </li>
            </ul>
    </div>
</div>
        
        

    </div> <!-- End Container -->

    <!-- Footer -->
    <footer class="text-center py-4">
        <p>¬© 2025 Actuated Experiences ¬∑ MIT</p>
    </footer>

    <!-- Bootstrap JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Script to Load Header -->
    <script src="../../js/load_header_labs.js"></script>
</body>
</html>