<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lab 4: Let‚Äôs make a Bahrain-themed Automata!
</title>
    <!-- Bootswatch Litera CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/litera/bootstrap.min.css" rel="stylesheet">
        <link rel="icon" type="image/x-icon" href="Media/Photos/Logo.svg">

    <link rel="stylesheet" href="../../styles.css"></link>
</head>
<body>

    <!-- Header Placeholder -->
    <div id="header-placeholder"></div>

    <!-- Main Container -->
    <div class="container" >
    <div class="row">
        <!-- Lab 1 Page Heading -->        
        <div class="col-md-4">
            <div class="sticky-top" style="padding-top:100px;" >
                <p>Total Time: 2.5 hours</p>
                <h5>Quick Links</h5>
                <ul>
                    <li><a href="#introduction">Introduction & Safety</a></li>
                    <li><a href="#software">Fabrication Quest</a></li>
                    <li><a href="#ppe">Software & Hardware for the Lab</a></li>
                    <li><a href="#machines">Part (1): Variables & Equations </a></li>
                    <li><a href="#assembly">  Part (2): Sketching Parametrically </a></li>
                    <li><a href="#testing"> Part(3): Extrusion </a></li>
                    <li><a href="#conclusion"> Part(4): Threaded Holes</a></li>
                      <li><a href="#machines">Part (5): Sketching Revolve Profiles </a></li>
                    <li><a href="#assembly">  Part (6): Revolving </a></li>
                    <li><a href="#testing"> Part(7): Extrude Cut</a></li>
                    <li><a href="#conclusion"> Part(8): UNderstanding Sketch Constraints</a></li>
                    <li><a href="#conclusion"> Part(9): Creating Blocks (REMIX) </a></li>
                    <li><a href="#conclusion"> Part(10): Material Assignment</a></li>
                     <li><a href="#conclusion"> Part(11): CAD Assemblies</a></li>
                    <li><a href="#conclusion"> Part(12): Rendering </a></li>
                    <li><a href="#conclusion"> Part(13): Export for 3D Printing </a></li>
                    <li><a href="#conclusion"> Part(14): Setting up File for 3D Printing </a></li>
                    <li><a href="#conclusion"> Discussion & Reflection </a></li>

                </ul>
            </div>
        </div>
        
        <!-- Introduction Section -->
        <div class="col-md-8" style="padding-top:100px;">
                <section class="mb-4">
                    <h1 class="mb-5">Lab 4: Mechanical Design with a Bahrain-themed Automata!</h1>
                    <img src=media/placeholder.png class="rounded mx-auto d-block img-fluid"> 
                    <h2> ü¶∫ Introduction & Safety</h2>(1 minute read) <br> <br>
                    <p>

                        
                     <p> Automata are mechanical devices designed to perform ‚Äúhuman/animal-like‚Äù actions. 
                        They usually serve a performative or artistic purpose and show a high level of 
                        craftsmanship and understanding of mechanism design. <a href="http://karakuri-tamaya.jp/en/knowledge.html"> Karakuri („Åã„Çâ„Åè„Çä) </a>  is the
                        Japanese term for automata, where the automata reflect stories or parts of Japanese
                        culture like a <a href="https://www.kitchenstudiofactory.com/rework-project/chahakobi-ningyo-japanese-tea-serving-automaton"> ‚ÄúChahakobi Ningyou‚Äù </a> which is an automata that bows as tea is being 
                        served.</p>   
                        
                    
                   <p>In this lab, you will explore CAMs, gears, and linkages to design automata. 
                       First, you'll learn the principles through a lecture and answer design
                       understanding questions.</p>
                    
                    <p>Next, in pairs, you'll design a Bahrain-themed automaton, 
                        inspired by cultural elements like Hiya Biya, Ramadan, Eid,
                        Gergaoon, palm trees, pearl diving...etc</p>
                        
                        
                    In this lab, you will <b> learn</b> how to: 
                    <br> <br> 
                    <ul>
                        <li> ‚úÖ Design CAMs, Gears, and linkages based on mechanical principles </li>
                        <li> ‚úÖ Design CAMs, Gears, and linkages in Fusion360</li>
                        <li> ‚úÖ Create Assemblies in Fusion360 for motion animation</li>
                        <li> ‚úÖ Design a Bahrain-themed automata from sketch, prototype, to final product</li>
                    </ul>

                </section>
                <hr>


                    <img src=media/placeholder.png class="rounded mx-auto d-block img-fluid  max-width: 10%"> 
                <br>
                    <h2>üî® Fabrication Quest of the Day</h2>
                <ul>
                    <li><strong>Today, you will CAD a Bahrain-themed automata that you will then lasercut. Your design 
                        guidelines are:</strong>
                        <br>
                        <ol>
    <li>Automata design must fit in a wood panel of XXcm by XXcm</li>
    <li> Your design must have a crank for manual actuation</li>
    <li>Use at least two motions via two different mechanisms (e.g., CAM and gear).</li>
    <li> Design a story and pick two motions you want by referring to the mechanism glossry tables
        (<a href=""> Table-1</a>, <a href=""> Table-2</a> ).</li>
    <li>Start with a shaft and add components.</li>
    <li>Base your design on Bahraini themes like Eid, Hiya Biya, or pearl diving.</li>
                            <li> Your design should hide the mechanism from view from the end that users will see it, 
                            and be able to see mecahnsim from the other end</li>
    <li>Keep it simple; complex automata take too long.</li>
   <li> Think ahead of how you want to add color; we will do this next lab but think ahead! </li>


                        
                        </ol>
                    </li>
                    
            <li><strong>Fabricated results will be for next lab, but  you will actuate your files through Fusion today,
                and upload your files for lasercutting to this <a href=""> Folder</a>; </strong>

<br> <br> 
            
                <hr>
                

                <!-- Materials Section -->
                <section class="mb-4">
                    <h2>üèóÔ∏è Software & Hardware</h2>


                    <h5>Software:</h5>
                        <ul>
                            <li> <a href="https://www.autodesk.com/education/edu-software/fusion"> Fusion360 </a> </li>
                            <li> Adobe Illustrator </li>
                    
                    </ul>

                </section>

                <hr>

                <!-- Procedure Section -->

                    
                    <!-- Part 1: Designing the Calendar -->
                    <h4>Part (0): Mechanism Glossary Tables (Refer to this As you Design)

</h4>
  <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/6S8xpPzyGAQ?si=et1cR-XHRD9FAPry" title="YouTube video player" allowfullscreen></iframe>
        </div>

     <br> 
                
                <!--note that thread size is 7mmx1mm by making a hole--> 
                <strong> Video Summary </strong> 
       
                <ol>
        <li>Dimensioning models through variables allows for model dimension modification with ease</li>
        <li> To create dimension variables go to: <b>  Modify -> Change Parameters -> Add User Parameter (top "+" sign) </b> </li>
                    <li>Create a variable for ‚Äúshaft_outer_d‚Äù representing the inner diameter of the Threaded Shaft, and set it to 9mm.</li>
        <li>Follow table below to add all the following variables, and one equation to your Fusion File Parameters. Don't forget to save as you go! </li>
    </ol>
                <br> 
                
                
                <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
        <th scope="col">Part Name (do not add to Fusion)</th>
      <th scope="col">Variable Name (add in Fusion)</th>
      <th scope="col">Expression</th>
      <th scope="col">Unit</th>
    </tr>
  </thead>
  <tbody>

      
    <tr>
      <th scope="row">2</th>
      <td> Shaft Outer Diamter</td>
      <td>shaft_outer_d</td>
      <td>9</td>
      <td>mm</td>


    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Shaft Length for 3 Rotating Blocks</td>
      <td>shaft_length_3b</td>
      <td>36.2 </td>
      <td>mm</td>
    </tr>
 
      
 
    <tr>
      <th scope="row">4</th>
      <td>Shaft Length for 4 Rotating Blocks</td>
      <td>shaft_length_4b</td>
      <td>48.2 </td>
      <td>mm</td>
    </tr>
      
          <tr>
      <th scope="row">5</th>
      <td>Shaft Threaded Hole Depth</td>
      <td>thread_depth</td>
      <td>10</td>
      <td>mm</td>
              

      
            <tr>
      <th scope="row">7</th>
      <td>Keychain Hole Diameter</td>
      <td>keychain_hole_d</td>
      <td>4</td>
      <td>mm</td>
    </tr>
               <tr>
      <th scope="row">9</th>
      <td>Rotating Block Size</td>
      <td>rot_b_size</td>
      <td>12</td>
      <td>mm</td>
    </tr>   
 
               <tr>
      <th scope="row">10</th>
      <td>Rotating Block thickness</td>
      <td>rot_b_thick</td>
      <td>12</td>
      <td>mm</td>
    </tr>
      
               <tr>
      <th scope="row">11</th>
      <td>Rotating Block Hole Tolerance</td>
      <td>tolerance</td>
      <td>0.6</td>
      <td>mm</td>
    </tr>  

                <tr>
      <th scope="row">12</th>
      <td>Rotating Block Hole Diameter</td>
      <td>rot_b_hole_d</td>
      <td>shaft_outer_d + tolerance</td>
      <td>mm</td>
    </tr>  
           
      
  </tbody>
</table>
                
                
                    <div class="alert alert-info" role="alert" style="background-color: #C94747; color: white;">
                        <h4>Checkoff 1</h4>
                        Ask your instructor for a check-off on completing Part (1)
                    </div>
        <br> 
                    <hr> 
                    
                    <h4>Part (2): Sketch and Dimension Parametrically  (Sketching Keychain Shaft) (5 minutes)</h4>

                    <img src=media/3dprinting-pt2.png class="rounded mx-auto d-block img-fluid"> 


                <br>
                
                <strong> Instructions </strong> 
       
             
                <br> 
                
        <ol>
        <li>Draw a circle at the center (0,0).</li>
        <li>Dimension the first circle with ‚Äúshaft_outer_d.‚Äù</li>
        <li> Exit Sketch, and rename the Sketch to "shaft-circle"</li>
                </ol>
                <br>
                
                üìç If you need a refresher on how to sketch or dimension, please visit <a href="lab1.html"> Lab 1</a> !
                <br> 
   
                    
         <hr>
                    <!-- Part 4: Assembly and Post-Processing -->
            <h4>Part (3): Extruding the Sketch (give height to the shaft!) (5 minutes)</h4>
                    
                    
                    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/X_iETFAja6o?si=us0xS1adUD31SdRx" title="YouTube video player" allowfullscreen></iframe>
        </div>

                            
            <br> 
                
                                <strong> Video Summary </strong> 
<br> 

                <ol>
        <li>Click on <strong>Create</strong>.</li>
        <li>Select the <strong>Extrude Tool</strong>.</li>
        <li>Under <strong>Profile</strong>, select the area formed by the circle from your "shaft-circle" sketch.</li>
        <li>Set the <strong>Direction</strong> to <strong>One Side</strong>.</li>
        <li>Type the <strong>Distance</strong> as ‚Äúshaft_length_3b‚Äù or "shaft_length_4b"-- here you must decide whether you
                    will make a 3 block or 4 block keychain; No worries if you change your mind later on! ü§ó</li>
        <li>Choose the operation as <strong>New Component</strong>.</li>
        <li>Click <strong>Ok</strong> to create the solid cylinder.</li>
                    <li> Write click on the component and <strong> Rename it</strong> to "Shaft"</li>
    </ol>
                
                <br> 
                   
        <hr>
            
                    <h4>Part (4): Making a Threaded Hole (7 minutes)</h4>

                
                
                    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/wXWqRJZoUgk?si=gpR0gE7b-c3LxezM" title="YouTube video player" allowfullscreen></iframe>
        </div>
                <br> 
<b> Video Summary (need to change): </b>   
            
                <ol>
        <li> Toggle "Shaft-circle" sketch back on</li>
        <li>Go to <strong>Create</strong>.</li>
        <li>Select the <strong>"Hole" Tool</strong>.</li>
        <li>Under <strong>Face</strong>, select the top face of the cylinder.</li>
        <li>Set the <strong>Reference</strong> to <strong>the center of the circle sketch</strong> (i.e. the "point" at the circle's center from the sketch).</li>
        <li>Set the <strong>Hole Type</strong> to <b> ‚ÄúSimple‚Äù </b></li>
        <li>Set the <strong>Hole Tap Type</strong> to <b> ‚ÄúTapped‚Äù </b></li>
        <li>Set the <strong>Thread Offset</strong> to <b> ‚ÄúFull‚Äù </b></li>
        <li>Set the <strong>Drill Point</strong> to <b> ‚ÄúAngle‚Äù </b></li>
        <li>Set the <strong>Depth</strong> to <b> "thread_depth" </b></li>
        <li>Set the <strong>Size</strong> to <b> 7mm </b></li>
         <li>Set the <strong>Designation</strong> to <b> M7mmx1mm </b></li>
         <li>Have <strong>Modeled</strong> checked <b> ON </b></li>
        <li>Click <strong>Ok</strong> to create your threaded hole.</li>
    </ol>
                <br> 
             
              <div class="alert alert-info" role="alert" style="background-color: #C94747; color: white;">

                        <h4>Checkoff 2</h4>
                    Show your shaft with its threaded hole to your instructor, and explain to them what M7mmx1mm means (you are encouraged to look up the answer online üëÄ)!
                    
                    </div>  
                

                <hr>

                                
                <hr> 
        <h4>Part (5): Creating Profile of Keychain Holder Head  (üö®REMIXüö®) (10 minutes)</h4>

                
                 <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/m07_IYGyhos?si=PRVqOGwR-EquRE_3" title="YouTube video player" allowfullscreen></iframe>
        </div>
                
                
            <ol>
        <li>
            <strong>Create an Axis Through the Cylinder:</strong>
            <ul>
                <li>Go to the <strong>Construct</strong> command in the top menu.</li>
                <li>Select <strong>Axis Through Cylinder</strong>.</li>
                <li>Click on the cylinder to establish the axis of rotation.</li>
            </ul>
        </li>
        <li>
            <strong>Create a Plane at an Angle to the Axis:</strong>
            <ul>
                <li>Again, in the <strong>Construct</strong> menu, select <strong>Plane at Angle</strong>.</li>
                <li>Click on the axis you created.</li>
                <li>Enter the angle as "0" for the plane, then confirm.</li>
            </ul>
        </li>
        <li>
            <strong>Use the Plane to Sketch the profile for the Top Holder on [üö® REMIX OPPORTUNITYüö®]:</strong>
            
                                <img src=media/revolve-profiles.png class="rounded mx-auto d-block img-fluid"> 

            
            <ul>
                <li>On the new plane, right click on it and select <strong>Create New Sketch</strong> (there are other ways 
                    of doing this, but we opt for right clicking on plane for now).</li>
                <li> To ensure we remain within bounds, go to <strong> Create</strong>, then <strong> Project</strong>, <strong> Select Entity (Selection Filter)</strong> and click on the perimeter of the top circle of the cylinder for <strong> Geometry</strong>. Kepp Projection Link on.
                
                <li> Your Design Constraints for your REMIX are as follows: </li>
                <li>Draw the profile you would be revolving for the top holder on this plane. Recall that this should be symmetric and should not extrude out too much. Make sure that the profile is <strong> closed!</strong></li>
                <li>Once done, click <strong>Finish Sketch</strong></li>
            </ul>
        </li>
    </ol>
                
                <br> 
                
                In the next step, we will revolve this profile to create a symmetric top keychain holder.
                    <br> 
                
                <div class="alert alert-info" role="alert" style="background-color: #C94747; color: white;">

                        <h4>Checkoff 4</h4>
        Show & explain your sketched profile to your instructor ensuring that your design meets Remix Design Constraints!           </div>
        <hr> 
                
                
                
                <h4>Part (6): Revolving Radially Symmetric Geometry(10 minutes)</h4>

            <strong> Video Summary:</strong>
                
                 <ol>
        <li><strong>Revolve Command:</strong> Go to <strong>Create &gt; Revolve</strong> in the toolbar.</li>
        <li><strong>Select Profile:</strong> Click on the profile (the closed shape) that you want to revolve.</li>
        <li><strong>Select Axis:</strong> Click the axis of symmetry (the cyliner axis we constructed) around which the profile will revolve.</li>
        <li><strong>Set Angle:</strong> In the Revolve dialog, set the <strong>angle</strong> to 360¬∞ (or the desired angle for partial revolution if you want to play around with this!).</li>
        <li><strong>OK:</strong> Click <strong>OK</strong> to complete the operation.</li>
    </ol>
        
            
                <br>

        <hr> 
                
                <hr> 
                
                
                
                <h4>Part (7): Making Hole for Keychain (5 minutes)</h4>
                
        <ol>
        <li><strong>Create a Tangent Plane:</strong> Create a plane that is tangent to the surface of your revolved part using <strong>Construct &gt; Tangent Plane</strong>.</li>
        <li><strong>Sketch a Circle on the Tangent Plane:</strong> Start a sketch on the tangent plane and draw a circle where you want the hole.</li>
        <li><strong>Dimension the Circle:</strong> Use the <strong>Dimension</strong> tool to set the circle's diameter to <strong>4mm</strong> (or your desired size).</li>
        <li><strong>Extrude Cut the Hole:</strong> Use <strong>Create &gt; Extrude</strong>, select the circle, and set it to <strong>Cut</strong> with the <strong>Symmetric</strong> direction to cut both sides of the part.</li>
        <li><strong>Finish:</strong> Click <strong>OK</strong> to complete the hole creation process.</li>
    </ol>
                
                <br> 
        <div class="alert alert-info" role="alert" style="background-color: #C94747; color: white;">

                        <h4>Checkoff 8</h4>
        Show your shaft's keychain hole to your instructor       </div>      
                <hr> 
                
                
                            <h4>Part (8): Understanding Sketch Relationships & Constraints (5 minutes)</h4>

                <hr> 

            <h4>Part (9): Creating Blocks (üö®REMIXüö®) (30 minutes)</h4>

                
                <i> As you create you <b> BLOCKS </b> we recommend creating them as <b>"New Components"</b> even though video shows Bodies
                </i>
                
              <br> <br> 
                
                 <p>Now is the time to be as ‚ú®creative‚ú® as you'd like! Create your keychain blocks by following the design guidelines outlined below, 
                     and refer to the video to guide through some steps to understand those guidelins. </p> 
                
                
                [VIDEO GOES HERE]
                
                <br> 
                <p> Below are some of your instructor's creations-- you might 
                also consider designing something in illustrator and importing as DXF (like what you learned in <a href="lab1.html"> Lab 1</a>), and as demonstrated in the video!</p>
              
  <img src=media/block_remix_no_material.png class="rounded mx-auto d-block img-fluid"> 

                
                <strong>Design Constraints Summary: </strong>
                <br> <br> 
                <ol> <li> Block Size: 12mm (variable: rot_b_size)  </li>
                 <li>  Hole Size:  9.6mm (variable: rot_b_hole_d)  </li>
                 <li>  General 3D Printing Guidelines:  <a href= "https://www.hydraresearch3d.com/design-rules"> Link1</a>, <a href="https://wikifactory.com/+wikifactory/stories/ultimate-guide-how-to-design-for-3d-printing"> Link2</a>
                    <ul> 
                     <li> Minimum Feature size:  2x Nozzle diameter (e.g. 0.8mm for 0.4mm Nozzle) </li>
                        <li> Angles (for minumum support material):  < 50 Degrees </li>
                     </ul></li></ol>
                <br> 
              

 <div class="alert alert-info" role="alert" style="background-color: #C94747; color: white;">

                        <h4>Checkoff 8</h4>
        Show your keychain blocks to your instructor & share your creative vision!       </div>        
                
                
        <h4>Part (10): Assigning Materials & Colors (15 minutes)</h4>

         <img src=media/block-examples.png class="rounded mx-auto d-block img-fluid"> 
                
                <ol>
        <li>
            <strong>Assign Material:</strong>
            <ul>
                <li>Right-click the <strong>body/component</strong> in the <strong>Browser</strong> and select <strong>"Appearance"</strong>.</li>
                <li>Drag a material from the <strong>Appearance</strong> panel to the body (whole body or specific faces).</li>
            </ul>
        </li>
        
        <li>
            <strong>Custom Color:</strong>
            <ul>
                <li>Right-click the applied material and choose <strong>"Edit"</strong>.</li>
                <li>Click the <strong>color box</strong> to select a <strong>custom color</strong>.</li>
            </ul>
        </li>
    </ol>

<hr> 
                
   <h4>Part (11): Assemblies in CAD (10 minutes)</h4>

             <ol>
        <li>
            <strong>Ensure Blocks Are Components:</strong>
            <ul>
                <li>Convert blocks to <strong>components</strong> by right-clicking and selecting <strong>"Convert to Component"</strong>.</li>
            </ul>
        </li>

        <li>
            <strong>Create Assembly:</strong>
            <ul>
                <li>Click <strong>"Assemble"</strong> > <strong>"Joint"</strong>.</li>
                <li>Choose the <strong>Shaft</strong> as <strong>Component 1</strong> and the first <strong>Block</strong> as <strong>Component 2</strong>.</li>
                <li>Define the joint type as <strong>"Simple"</strong>.</li>
            </ul>
        </li>

        <li>
            <strong>Add Remaining Blocks:</strong>
            <ul>
                <li>For <strong>bodies</strong>, use <strong>"Align Relationships"</strong>.</li>
                <li>For <strong>components</strong>, apply <strong>"Joint"</strong> again.</li>
            </ul>
        </li>
    </ol>   

            <hr> 
                
                 <h4>Part (12): Rendering (5 minutes)</h4>
                
  <img src=media/block-examples-rendered.png class="rounded mx-auto d-block img-fluid"> 

                <ol>
        <li>
            <strong>Switch to Render Workspace:</strong>
            <ul>
                <li>Click on the <strong>Design</strong> tab and switch to the <strong>Render</strong> workspace.</li>
            </ul>
        </li>

        <li>
            <strong>Adjust Scene Settings:</strong>
            <ul>
                <li>Click on <strong>Scene Settings</strong> to adjust the lighting and background to your liking.</li>
            </ul>
        </li>

        <li>
            <strong>Render and Save Image:</strong>
            <ul>
                <li>Click on <strong>In-Canvas Render</strong> to generate the render.</li>
                <li>Once done, save the image to your computer.</li>
            </ul>
        </li>
    </ol>

                
            <hr> 

                
 <h4>Part (13): Export for 3D Printing (5 minutes)</h4>

                    <ol>
        <li>
            <strong>Export the 3D Model:</strong>
            <ul>
                <li>Click <strong>File</strong> in the top-left corner, then select <strong>3D Print</strong>.</li>
            </ul>
        </li>
        
        <li>
            <strong>Use the 3D Print Utility:</strong>
            <ul>
                <li>Click on <strong>3D Print from Utility</strong>.</li>
                <li>Choose <strong>Application Custom</strong>, and then <strong>load CURA</strong> from your applications list.</li>
            </ul>
        </li>

        <li>
            <strong>Open in Cura:</strong>
            <ul>
                <li>After selecting your model, click <strong>OK</strong>.</li>
                <li><strong>CURA</strong> will open automatically with the selected model.</li>
            </ul>
        </li>

        <li>
            <strong>Export Each Component:</strong>
            <ul>
                <li>Repeat the process for each component to export them one by one.</li>
            </ul>
        </li>
    </ol>
                
                
  <hr> 
                
                
  <h4>Part (14): Setting Up File for 3D Printing (10 minutes)</h4>

<ol>
        <li>
            <strong>Adjust Model Orientation:</strong>
            <ul>
                <li>Ensure your models are in the correct orientation.</li>
                <li>Use <strong>Rotate</strong> and <strong>Move</strong> tools to adjust the position if needed.</li>
                <li>Make sure models do not overlap.</li>
            </ul>
        </li>
        
        <li>
            <strong>Adjust 3D Printing Settings:</strong>
            <ul>
                <li>Set <strong>Layer Thickness</strong> to <strong>0.1mm</strong> (fine quality, for threading).</li>
                <li>Set <strong>Speed</strong> to <strong>100mm/s</strong>.</li>
                <li>Set <strong>Fill Density</strong> to <strong>15%</strong>.</li>
                <li>Enable <strong>Support</strong> (set to "only touching the print bed").</li>
                <li>Disable <strong>Build Plate Adhesion</strong> (usually recommend to use brim, but here we just don't want to 
                    affect your design).</li>
            </ul>
        </li>

        <li>
            <strong>Slicing and Preview:</strong>
            <ul>
                <li>Click <strong>Slice</strong> to generate the G-code.</li>
                <li>Click <strong>Preview</strong> to check your print setup before exporting.</li>
            </ul>
        </li>
    </ol>
                <hr> 
                
                <!-- Submission Section -->
                <section class="mb-4">
                    <h2>Discussion & Reflections</h2>
        <ol>
            <li><strong>Discuss the advantages and limitations of using 3D Printing for digital fabrication.</strong>
                <ul>
                    <li>What can we make? What is difficult to make?</li>
                </ul>
            </li>
            <li><strong>Reflect on the design process</strong> 
                <ul>
                    <li>Consider any modifications that could have improved/elevated youre remix design.</li>
                </ul>
            </li>
            
        </ol>
                </section>
                
                    </li>
            </ul>
    </div>
</div>
        
        

    </div> <!-- End Container -->

    <!-- Footer -->
    <footer class="text-center py-4">
        <p>¬© 2025 Actuated Experiences ¬∑ MIT</p>
    </footer>

    <!-- Bootstrap JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Script to Load Header -->
    <script src="../../js/load_header_labs.js"></script>
</body>
</html>